const conferences = [
  {
    title: 'TechXpresso Chennai 2026',
    description: 'Testing Autonomous AI Agents: Beyond Traditional QA',
    imageURL: '',
    url: '',
    reverse: false,
    tags: ['AI', 'Agents', 'Testing', 'Quality'],
  },
  {
    title: 'NullCon Goa 2026',
    description: 'Hacking with AI: MCP for Security Testing',
    imageURL: '',
    url: '',
    reverse: false,
    tags: ['AI', 'MCP', 'Security', 'Testing'],
  },
  {
    title: 'Automation Guild 2026',
    description: 'Testing Autonomous AI Agents: A QA Practitioner\'s Guide',
    imageURL: '',
    url: 'https://testguild.com/automation-guild-2026/',
    reverse: true,
    tags: ['AI', 'Agents', 'Testing', 'Quality'],
  },
  {
    title: 'TestCon Europe 2025',
    description: 'Testing Agentic AI Applications: Beyond Traditional QA',
    imageURL: '',
    url: 'https://www.testconeurope.com/',
    reverse: false,
    tags: ['AI', 'Agentic', 'Testing', 'Quality'],
  },
  {
    title: 'TestMu Conf 2025',
    description:
      'Mastering Appium 3: Architecture, Gestures & Beyond and Testing the Untestable: QA Strategies for Autonomous AI Agents',
    imageURL: '',
    url: 'https://www.testmuai.com/testmuconf-2025/',
    reverse: true,
    tags: ['AI', 'Appium', 'MCP', 'Agents'],
  },
  {
    title: 'SeleniumConf & AppiumConf Valencia 2025',
    description: 'Beyond DOM: Leveraging Open-Source LLMs in an AI-Powered Appium Plugin',
    imageURL: '',
    url: 'https://youtu.be/lugEm6j1Nl8',
    reverse: false,
    tags: ['Mobile', 'Appium', 'AI', 'LLM'],
  },
  {
    title: 'Nordic Testing Days 2025',
    description: 'Advanced Appium Workshop: Simplifying Mobile Test Automation',
    imageURL: '',
    url: 'https://nordictestingdays.eu/',
    reverse: true,
    tags: ['Mobile', 'Appium', 'Testing', 'Workshop'],
  },
  {
    title: 'Spartans Summit 2025',
    description: 'Building and Testing AI-Agent Powered LLM Applications',
    imageURL: '',
    url: 'https://www.youtube.com/watch?v=9mHfvGN7FwU',
    reverse: false,
    tags: ['AI', 'LLM', 'Agents', 'Testing'],
  },
  {
    title: 'HUSTEF 2024',
    description: "Mobile App Crashes in Production: Lessons Learned from a Tester's Viewpoint",
    imageURL: '',
    url: 'https://hustef.com/',
    reverse: true,
    tags: ['Mobile', 'Testing', 'Quality', 'Crashes'],
  },
  {
    title: 'SeleniumConf 2024',
    description: 'Harnessing Power of Open-Source: Building a Cutting-Edge Device Farm',
    imageURL: '',
    url: '',
    reverse: false,
    tags: ['Open Source', 'Device Farm', 'Testing'],
  },
  {
    title: 'AppiumConf 2024',
    description: 'The Performance Paradox: Navigating the Complexities of Modern Mobile App Optimisation',
    imageURL: '',
    url: '',
    reverse: true,
    tags: ['Mobile', 'Appium', 'Performance'],
  },
  {
    title: 'Spartans Summit 2024',
    description: 'Unveiling the Power of Web Performance Metrics for Testers',
    imageURL: '',
    url: 'https://www.youtube.com/watch?v=uo_lX1pUv9o',
    reverse: false,
    tags: ['Performance', 'Web', 'Testing', 'Metrics'],
  },
  {
    title: 'SeleniumConf Chicago 2023',
    description: 'Clean Code Practices for Test Automation & Advanced Appium 2.0 Workshop',
    imageURL: '',
    url: '',
    reverse: true,
    tags: ['Appium', 'Clean Code', 'Testing'],
  },
  {
    title: 'XConf Singapore 2023',
    description: 'Path to a more equitable testing process: Addressing unconscious bias and ethics',
    imageURL: '',
    url: 'https://youtu.be/QMr30Za_-vM',
    reverse: false,
    tags: ['Ethics', 'Bias', 'Testing'],
  },
  {
    title: 'TestMu Conf 2023',
    description: 'Elevate your testing game: Building Appium 2.0 plugin Live',
    imageURL: '',
    url: 'https://www.youtube.com/watch?v=b6yWXfLpazc',
    reverse: true,
    tags: ['Mobile', 'Appium', 'Testing'],
  },
  {
    title: 'VodQA Singapore 2023',
    description: "Navigating mobile app testing challenges in today's tech landscape",
    imageURL: '',
    url: '',
    reverse: false,
    tags: ['Mobile', 'Challenges', 'Testing'],
  },
  {
    title: 'SeleniumConf 2022',
    description: 'Build your own Appium 2.0 Driver',
    imageURL: '',
    url: '',
    reverse: true,
    tags: ['Mobile', 'Appium', 'Selenium'],
  },
  {
    title: 'TestMu Conf 2022',
    description: "Appium: Endgame & What's Next?",
    imageURL: '',
    url: '',
    reverse: false,
    tags: ['Mobile', 'Appium', 'Testing'],
  },
  {
    title: 'Automation Guild 2022',
    description: 'Benefits and Best Practices: Testing Containers & k8s Manifests',
    imageURL: '',
    url: '',
    reverse: true,
    tags: ['Containers', 'Kubernetes', 'Testing'],
  },
  {
    title: 'Worqference 2022',
    description: 'Automate Mobile Gestures Using Appium',
    imageURL: '',
    url: '',
    reverse: false,
    tags: ['Mobile', 'Appium', 'Gestures'],
  },
  {
    title: 'Agile India 2022',
    description: 'Speed Matters: Client Side Performance Improvement Tips & Tricks',
    imageURL: '',
    url: '',
    reverse: true,
    tags: ['Performance', 'UI', 'Testing'],
  },
  {
    title: 'AppiumConf 2021',
    description: 'Build your own Appium plugin',
    imageURL: '',
    url: '',
    reverse: false,
    tags: ['Appium', 'Mobile', 'Plugins'],
  },
  {
    title: 'Agile India 2021',
    description: 'Testing Service Mesh configs and k8s manifests',
    imageURL: '',
    url: '',
    reverse: true,
    tags: ['Agile', 'DevOps', 'Kubernetes'],
  },
  {
    title: 'Automation Guild 2021',
    description: 'Consumer Driven Contracts',
    imageURL: '',
    url: '',
    reverse: false,
    tags: ['Testing', 'Contracts', 'API'],
  },
  {
    title: 'Future of Testing: Mobile 2021',
    description: "Appium 2.0: What's Next",
    imageURL: '',
    url: 'https://applitools.com/future-of-testing-mobile-apac-2021/',
    reverse: true,
    tags: ['Mobile', 'Appium', 'Testing'],
  },
  {
    title: 'SeleniumConf 2020',
    description: 'Advanced Appium Workshop & Appium-Android: From Surface To Core',
    imageURL: '',
    url: '',
    reverse: false,
    tags: ['Mobile', 'Appium', 'Android'],
  },
  {
    title: 'SLASSCOM Quality Summit 2019',
    description: 'Shift Left for Better End-User Experience',
    imageURL: '',
    url: '',
    reverse: true,
    tags: ['Quality', 'Shift Left', 'Testing'],
  },
  {
    title: 'AppiumConf 2019',
    description: 'Life Cycle of an Appium Command & Native Mobile Commands in Appium',
    imageURL: '',
    url: '',
    reverse: false,
    tags: ['Mobile', 'Appium', 'Testing'],
  },
  {
    title: 'SeleniumConf Bangalore 2018',
    description: 'Code Once Test Anywhere: On Demand Private Appium Device Cloud using ATD',
    imageURL: '',
    url: '',
    reverse: true,
    tags: ['Mobile', 'Appium', 'Device Farm'],
  },
  {
    title: 'SeleniumConf Barcelona 2018',
    description: 'Next Level of Front-end Testing with DevTools and WebDriver',
    imageURL: '',
    url: '',
    reverse: false,
    tags: ['Frontend', 'DevTools', 'WebDriver'],
  },
  {
    title: 'Belgrade Test Conference 2018',
    description: 'On Demand Private Appium Device Cloud',
    imageURL: '',
    url: '',
    reverse: true,
    tags: ['Mobile', 'Appium', 'Device Farm'],
  },
  {
    title: 'Quest for Quality Dublin 2018',
    description: 'On Demand Private Appium Device Cloud using ATD',
    imageURL: '',
    url: '',
    reverse: false,
    tags: ['Mobile', 'Appium', 'Device Farm'],
  },
  {
    title: 'FOSDEM Brussels 2017',
    description: 'Future of Mobile Automation Testing, Appium Steals It',
    imageURL: '',
    url: 'https://video.fosdem.org/2017/H.2213/mobile_testing_with_appium.mp4',
    reverse: true,
    tags: ['Mobile', 'Appium', 'Open Source'],
  },
  {
    title: 'SeleniumConf Austin 2017',
    description: 'Test Inside Containers: Dockerize Appium Tests',
    imageURL: '',
    url: 'https://youtu.be/jGW6ycW_tTQ',
    reverse: false,
    tags: ['Mobile', 'Appium', 'Docker', 'Containers'],
  },
]

export { conferences }
